//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int IdCostumer { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Password { get; set; }
        public string Mail { get; set; }
    }
}
